Feature/jaeger
fsd-nodejs/service-mw2 pull request #62
Opened 2021-05-08 10:32 UTC by Carb-X

jeager链路追踪

2021-05-08 11:14 UTC, waitingsong commented on README.md
> +Jaeger是[OpenTracing](https://opentracing.io/docs/)的一个实现，链路追踪是一个比较复杂的话题，关于Jaeger的具体用法请参考[它的官方文档](https://www.jaegertracing.io/docs/1.22/)
英文单词前后合适地加入空格

2021-05-08 15:10 UTC, waitingsong requested changes

2021-05-08 15:10 UTC, waitingsong commented on test/util/tracer.test.ts
> +  it('should not works if unenabled', async () => {
英文没有 unenabled 这个单词，应该使用 disabled

2021-05-09 06:21 UTC, Carb-X commented on README.md
> +Jaeger是[OpenTracing](https://opentracing.io/docs/)的一个实现，链路追踪是一个比较复杂的话题，关于Jaeger的具体用法请参考[它的官方文档](https://www.jaegertracing.io/docs/1.22/)
ok

2021-05-09 06:21 UTC, Carb-X commented on test/util/tracer.test.ts
> +  it('should not works if unenabled', async () => {
哈哈哈，我傻了

2021-05-09 07:08 UTC, tkvern commented
@Carb-X 代码ok，CI 还有些问题，你那边可以跑通么

2021-05-09 07:09 UTC, tkvern approved these changes

2021-05-09 07:13 UTC, Carb-X commented
> @Carb-X 代码ok，CI 还有些问题，你那边可以跑通么

我这边跑的通的，我改改再提交下

2021-05-09 07:28 UTC, tkvern commented on src/app/middleware/tracer-middleware.ts
> +  if (ctx.app.config.tracer.whiteList.includes(ctx.path)) {
这里还需增加测试用例覆盖到

2021-05-09 07:28 UTC, tkvern commented on src/app/util/tracer.ts
> +      return {};
这块也是

2021-05-09 07:36 UTC, Carb-X commented on src/app/util/tracer.ts
> +      return {};
ok

2021-05-10 06:53 UTC, tkvern approved these changes

2021-05-10 06:55 UTC, merged